debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

  [entryPoints.dashboard]
    address=":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        usersFile = "/etc/traefik/.htpasswd"

[api]
entrypoint = "dashboard"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "greymatterbay.com"
watch = true
exposedByDefault = false

[acme]
email = "kajohterna@gmail.com"
storage = "/etc/traefik/acme/acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

  [[acme.domains]]
    main = "greymatterbay.com"
    sans = ["app.greymatterbay.com", "blog.greymatterbay.com"]